### PR TITLE
Django 1.10 support

### PR DESCRIPTION
**Pull request by mbeacom**
- Added Django 1.10 entry to travis.
- Modified README.md to reflect new Django version range.
- Removed deprecated `patterns` usage.
- Modified all `render_to_response` references to `render` to simplify `context_instance` parameter deprecation and removed unused `RequestContext` import.
- Dropped support for Django < 1.8.

### CODE REVIEW

**Comment by mbeacom** [comment]
@nicholasserra Do you plan to drop support for any previous Django releases?  I only ask because `django-redis-cache` has dropped support for Django < 1.8 in their latest `1.7.0` release, so you'll want to pin to `django-redis-cache==1.6.5`.

Also, `SimpleTestCase.urls` is deprecated in Django 1.10.  The recommended change is to use the `override_settings` decorator which is present in Django >= 1.7.  I'm going to commit a change that doesn't use the decorator for now to maintain compatibility.

Thanks

**Comment by nicholasserra** [comment]
Nice. Thanks for the patch. I think since django-redis-cache is basically a requirement, that we can safely follow along with their Django version requirements and drop support for Django < 1.8 in this new release.

**Comment by nicholasserra** [comment]
Merged and released to pypi. Thanks again :D

**Comment by mbeacom** [comment]
No problem.  Thank you for the repo!

**Pull request merged**
